{
  "projects": [
  { "nam":"丝渡造型官网" , "thumb":"img/product/pro1/th1.jpg" , "tag":"JQuery TweenMax 整屏滚动" , "link":"misa.dreamibaby.com" , "decription":"Pixel Design is startup company. PD specializes in creating logos and branding. They have own stationery printed for clients.The logo has been created in combination of two letters P + D. It was created about 10 logos. Finally, we chose one of them by the end of the refinement. For the logo was created brandbook and complete visual identity.<br/><br/>Additionally I create simple landing page intro website. On the website is videos & images slider. Moreover is content of the services and contact. The plan is to create an online store. More on website soon" , "pic1":"img/product/pro1/pic1.jpg","pic2":"img/product/pro1/pic2.jpg","pic3":"img/product/pro1/pic3.jpg"},
  { "nam":"Ctrip主页" , "thumb":"img/product/ctrip/ctth.jpg" , "tag":"Html&css 兼容IE", "link":"ctrip.dreamibaby.com" , "decription":"携程官网首页静态页面加css3缩放携程官网首页静态页面加css3缩放携程官网首页静态页面加css3缩放" , "pic1":"img/product/ctrip/pic1.jpg","pic2":"img/product/ctrip/pic2.jpg","pic3":"img/product/ctrip/pic3.jpg"},
  { "nam":"JQuery主页", "thumb":"img/product/jqlx/jqth.jpg", "tag":"响应式", "link":"jq.dreamibaby.com" , "decription":"根据media屏幕适配百分比缩放制作出能支持各种屏幕大小的兼容页面根据media屏幕适配百分比缩放制作出能支持各种屏幕大小的兼容页面根据media屏幕适配百分比缩放制作出能支持各种屏幕大小的兼容页面" , "pic1":"img/product/jqlx/pic1.jpg","pic2":"img/product/jqlx/pic2.jpg","pic3":"img/product/jqlx/pic3.jpg"},
  { "nam":"Taobao移动端", "thumb":"img/product/tb/tbth.jpg", "tag":"Html5&css3 移动端", "link":"tb.dreamibaby.com" , "decription":"淘宝移动端页面淘宝移动端页面淘宝移动端页面淘宝移动端页面淘宝移动端页面淘宝移动端页面淘宝移动端页面" , "pic1":"img/product/tb/pic1.jpg","pic2":"img/product/tb/pic2.jpg","pic3":"img/product/tb/pic3.jpg"},
  { "nam":"挑战手速", "thumb":"img/product/lx1/lxth.jpg", "tag":"js小游戏", "link":"lx1.dreamibaby.com" , "decription":"移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏移动端PC端js小游戏" , "pic1":"img/product/lx1/pic1.jpg","pic2":"img/product/lx1/pic2.jpg","pic3":"img/product/lx1/pic3.jpg"},
  { "nam":"小练习", "thumb":"img/product/lx2/lxth.jpg", "tag":"js小练习合集 知识点", "link":"lx2.dreamibaby.com" , "decription":"知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集知识点合集小练习合集" , "pic1":"img/product/lx2/pic1.jpg","pic2":"img/product/lx2/pic2.jpg","pic3":"img/product/lx2/pic3.jpg"}
]
}